services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    restart: always
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
